# -*- coding: utf-8 -*-
"""retriever

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KwdpkNiEKmkJJ_zALjFfQLmM3R8xogd_
"""

from typing import List, Dict, Any

import numpy as np
from sentence_transformers import SentenceTransformer

from vector_store import VectorStore


MODEL_NAME = "BAAI/bge-small-en-v1.5"


class Retriever:
    #retriever wraps SentenceTransformer encoder and VectorStore (FAISS + texts + metadatas)

    def __init__(self, model_name: str = MODEL_NAME) -> None:
        print(f"[RETRIEVER] Loading encoder: {model_name}")
        self.model = SentenceTransformer(model_name)

        print("[RETRIEVER] Loading VectorStore ...")
        self.store = VectorStore()

    def embed_query(self, query: str) -> np.ndarray:
        emb = self.model.encode(
            query,
            normalize_embeddings=True,
            convert_to_numpy=True,
        ).astype("float32")
        return emb  # shape: (dim,)

    def retrieve(self, query: str, k: int = 5) -> List[Dict[str, Any]]:
        #top-k retrieval with metadata
        if k < 3:
            k = 3

        print(f"[RETRIEVER] Embedding query: {query!r}")
        q_emb = self.embed_query(query)

        print(f"[RETRIEVER] Searching top-{k} in VectorStore ...")
        results = self.store.search(q_emb, k=k)
        return results


def main():
    #simple manual test
    r = Retriever()
    query = "factors that influence box office performance"
    results = r.retrieve(query, k=5)

    print("\n[RETRIEVER] Sample results:")
    for i, r_i in enumerate(results, start=1):
        meta = r_i["metadata"]
        src = meta.get("source", "unknown")
        title = meta.get("title", "N/A")
        print(f"\nResult {i}:")
        print(f"  Score:   {r_i['score']:.4f}")
        print(f"  Source:  {src}")
        print(f"  Title:   {title}")
        print(f"  Preview: {r_i['text'][:200].replace('\\n', ' ')} ...")


if __name__ == "__main__":
    main()
